### ISSUE TITLE
sky-cinema-harry-potter-hd.png

### ISSUE THREAD

**Issue by sgse** [gigablue-support-org/templates_PiconsUpdater#10]
![sky-cinema-harry-potter-hd](https://cloud.githubusercontent.com/assets/17575778/20038310/b6e66ee0-a431-11e6-9791-4373bffe07ae.png)

http://www.opena.tv/plugins/4023-piconsupdater-post259864.html#post259864

**Comment by sgse** [comment]
![sky-cinema-harry-potter](https://cloud.githubusercontent.com/assets/17575778/20038423/8eba5844-a433-11e6-957a-cb77da0505c0.png)

**Comment by arn354** [comment]
thx
