### ISSUE TITLE
channelsNotFoundList_SalzburgAG

### ISSUE THREAD

**Issue by sgse** [gigablue-support-org/templates_PiconsUpdater#11]
From [http://www.opena.tv/plugins/4023-piconsupdater-post260277.html#post260277](url)

[channelsNotFoundList_SalzburgAG.zip](https://github.com/gigablue-support-org/templates_PiconsUpdater/files/583205/channelsNotFoundList_SalzburgAG.zip)

Thank you in advance.

**Comment by arn354** [comment]
https://github.com/gigablue-support-org/templates_PiconsUpdater/commit/6e753d0c98506dc01dce0919fb1f4cd5095a9fbe
