### ISSUE TITLE
4 old picon with stupid new names from tv-hoster, 1 new

### ISSUE THREAD

**Issue by sgse** [gigablue-support-org/templates_PiconsUpdater#12]
Hello contributors,

New
![salzburg-ag-tv-hd](https://cloud.githubusercontent.com/assets/17575778/20227009/c0f66f80-a84a-11e6-9a85-6506c84fcf41.png)
Old with new name
![ard-one-hd](https://cloud.githubusercontent.com/assets/17575778/20227027/d247c1da-a84a-11e6-8fbf-c931ef42a07b.png)
![dw-tv-europa](https://cloud.githubusercontent.com/assets/17575778/20227028/d24838e0-a84a-11e6-9764-cf9410f060a4.png)
![bbc-entertainment-europe](https://cloud.githubusercontent.com/assets/17575778/20227030/d24953d8-a84a-11e6-926b-0c53979193c9.png)
![orf-2-s-hd](https://cloud.githubusercontent.com/assets/17575778/20227029/d2493312-a84a-11e6-808b-5ba51075af16.png)
Is zip better?
[git_arn354.zip](https://github.com/gigablue-support-org/templates_PiconsUpdater/files/586587/git_arn354.zip)
Reported by [http://www.opena.tv/plugins/4023-piconsupdater-post260928.html#post260928](url)
If possible, take over and install.
Thanks in advance
greetings sgse

**Comment by arn354** [comment]
zip ist einfacher
noch einfacher wäre ein direkter pull-request ;)

**Comment by sgse** [comment]
:-)
oh man, wenn mal einer die Seite (git) in deutsch übersetzen würde ;)
gäbe es eine Chance das ich es pull-requesten könnte :-D
Beim nächsten mal starte ich einen Versuch, aber nicht schimpfen wenn ich es versemmel :-)

**Comment by arn354** [comment]
ist eigentlich ganz einfach
1.) Du hast einen github account
2.) Du forkst die repository hier auf deinen github account
3.) Du fügst neue picons bei dir hinzu im Ordner picon_all - entweder über "upload files" im Netz auf Github oder Du nimmst ein x-beliebiges git programm (github für windows, Sourcetree,...)
![11-11-_2016_22-12-43](https://cloud.githubusercontent.com/assets/4148122/20230432/3d3727b8-a85c-11e6-8054-210496fea790.jpg)
4.) Nachdem hinzugefügt klickst du auf pullrequest - dann vergleicht er deinen "Fork" mit dem Original hier und schlägt eigentlich deine Änderungen/Ergänzungen vor. Bemerkungstext dazu und Pull-Request absenden.
5.) dann kommt das hier unter "Pull Requests" und ich bekomme eine Benachrichtigung.

**Comment by sgse** [comment]
Anders als ich gedacht habe ;-) , gut erklärt. Da kann ja nichts mehr schief gehen :-)
Dann forke ich mal :-D
Dankeschön :-)

**Comment by sgse** [comment]
Muss ich das zwei mal abschicken
![20161111-19](https://cloud.githubusercontent.com/assets/17575778/20231315/08fdd028-a861-11e6-9bf0-c0460c8937a4.png)

**Comment by arn354** [comment]
hab dir drüben kommentiert.

Du hast bei dir einen neuen branch sgse-patch-1 erstellt (normal geht das auch direkt im master, dann kannst dir den schritt sparen).
Du musst jetzt erstmal den "Merge pull request" klicken. So sieht das dann im übrigen bei mir dann aus, wenn ich was von dir kriege.
Nachdem gemerged - mach nochmal pullrequest im branch master bei dir - achte auf du/master nach mir/master.
