### ISSUE TITLE
DVB-T2 HD Regional

### ISSUE THREAD

**Issue by gnubbel** [gigablue-support-org/templates_PiconsUpdater#27]
SAT.1 HD = SAT.1 HD Bayern
RTL HD = RTL HD Muenchen

und

alpha HD = ARD-alpha HD

**Comment by sgse** [comment]
Hallo @gnubbel ,
kannst du bitte den Text aus der channelnotfounflist.txt hier an fügen ala
`rtl-hd-hbnds.png;/tmp/piconsupdater/picons-all/1_0_1F_4208_4003_2114_EEEE0000_0_0_0.png;https://raw.github.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/rtl-hd-hbnds.png`

**Comment by gnubbel** [comment]
Picons not found for '40' channels

munchentv-hd.png;/tmp/piconsupdater/picons-all/1_0_19_CBA7_431_1_FFFF01CA_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/munchentv-hd.png
vodafone-info-channel.png;/tmp/piconsupdater/picons-all/1_0_1_CF17_2726_F001_FFFF0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/vodafone-info-channel.png
sat1-hd-bayern.png;/tmp/piconsupdater/picons-all/1_0_1F_422B_4036_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/sat1-hd-bayern.png
rtl-hd-muenchen.png;/tmp/piconsupdater/picons-all/1_0_1F_420B_4006_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/rtl-hd-muenchen.png
ard-alpha-hd.png;/tmp/piconsupdater/picons-all/1_0_1F_323_3103_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/ard-alpha-hd.png
bloomberg-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4281_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/bloomberg-connect.png
1-2-3tv-connect.png;/tmp/piconsupdater/picons-all/1_0_1_428C_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/1-2-3tv-connect.png
cnn-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4282_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/cnn-connect.png
comedy-central-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4298_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/comedy-central-connect.png
couchplay-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4289_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/couchplay-connect.png
der-aktionar-tv-connect.png;/tmp/piconsupdater/picons-all/1_0_1_428D_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/der-aktionar-tv-connect.png
euronews-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4283_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/euronews-connect.png
eotv-connect.png;/tmp/piconsupdater/picons-all/1_0_1_428A_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/eotv-connect.png
france24-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4284_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/france24-connect.png
freenet-tv-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4280_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/freenet-tv-connect.png
hopechannel-connect.png;/tmp/piconsupdater/picons-all/1_0_1_428E_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/hopechannel-connect.png
insight-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4286_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/insight-connect.png
itsintv-connect.png;/tmp/piconsupdater/picons-all/1_0_1_428B_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/itsintv-connect.png
lokal-tv-connect.png;/tmp/piconsupdater/picons-all/1_0_1_428F_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/lokal-tv-connect.png
mediaspar-tv-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4290_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/mediaspar-tv-connect.png
mtv-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4297_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/mtv-connect.png
n24-doku-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4295_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/n24-doku-connect.png
nhk-world-tv-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4285_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/nhk-world-tv-connect.png
qvc-beauty-___and___-style-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4291_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/qvc-beauty-___and___-style-connect.png
qvc-plus-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4292_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/qvc-plus-connect.png
rhein-main-tv-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4293_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/rhein-main-tv-connect.png
sonnenklar-tv-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4294_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/sonnenklar-tv-connect.png
spiegel-tv-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4287_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/spiegel-tv-connect.png
sportdigital-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4288_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/sportdigital-connect.png
tlc-connect.png;/tmp/piconsupdater/picons-all/1_0_1_4296_4072_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/tlc-connect.png
wdr-hd-koln-internet.png;/tmp/piconsupdater/picons-all/1_0_1F_806_3103_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/wdr-hd-koln-internet.png
test-technique-uhd-nrj.png;/tmp/piconsupdater/picons-all/1_0_1F_12E_419_1_C00000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/test-technique-uhd-nrj.png
hlg-teststream.png;/tmp/piconsupdater/picons-all/1_0_1F_12D_419_1_C00000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/hlg-teststream.png
insight-tv-uhd.png;/tmp/piconsupdater/picons-all/1_0_1F_7D0_449_1_C00000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/insight-tv-uhd.png
insight-tv-uhd-spain.png;/tmp/piconsupdater/picons-all/1_0_1F_7D1_449_1_C00000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/insight-tv-uhd-spain.png
insight-uhd-russia.png;/tmp/piconsupdater/picons-all/1_0_1F_7D5_449_1_C00000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/insight-uhd-russia.png
pearl-tv-4k-uhd.png;/tmp/piconsupdater/picons-all/1_0_1F_7DA_449_1_C00000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/pearl-tv-4k-uhd.png
ses-uhd-demo-channel.png;/tmp/piconsupdater/picons-all/1_0_1F_1_40B_1_C00000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/ses-uhd-demo-channel.png
uhd1-by-astra-hd___plus___.png;/tmp/piconsupdater/picons-all/1_0_1F_2_40B_1_C00000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/uhd1-by-astra-hd___plus___.png
canal___plus___-uhd.png;/tmp/piconsupdater/picons-all/1_0_1F_3E9_456_1_C00000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/canal___plus___-uhd.png

**Comment by sgse** [comment]
Weil es mehr als drei sind :)
[NotFound.txt](https://github.com/gigablue-support-org/templates_PiconsUpdater/files/883024/NotFound.txt)

**Comment by gnubbel** [comment]
Feststellung oder Frage oder Anforderung. Sry versteh i net ;)

**Comment by sgse** [comment]
Ich hab es für mich gemacht und für dich als Hinweis. Ist hier etwas unübersichtlich (lang) ;-)

**Comment by gnubbel** [comment]
Verstanden, werde mich bessern.

**Comment by sgse** [comment]
Kann nach dem einpflegen geschlossen werden.
[https://github.com/gigablue-support-org/templates_PiconsUpdater/pull/26](url)
