### ISSUE TITLE
Please check the picon name

### ISSUE THREAD

**Issue by sgse** [gigablue-support-org/templates_PiconsUpdater#29]
Hi,
new picon from stefanbenno6 [https://www.opena.tv/plugins/4023-piconsupdater-post295507.html#post295507](url) + gala2.png from me.
I am not shure about the name I set (all without arte+arte-hd).
![linux5](https://cloud.githubusercontent.com/assets/17575778/24683431/4814e544-199f-11e7-8c51-531b00c0ccd4.png)
Adjusted to size (picon)
[last.zip](https://github.com/gigablue-support-org/templates_PiconsUpdater/files/894776/last.zip)

Can I upload it?

**Comment by arn354** [comment]
sieht man ja im log wie das picon heissen sollte. Ich weiß das nicht :)

**Comment by sgse** [comment]
Dann mach ich erstmal arte und warte ... ;)
was stefanbenno6 antwortet :)

**Comment by sgse** [comment]
Habe keine Rückmeldung bekommen also nehme ich die Namen die stefanbenno6  benutzt.
