### ISSUE TITLE
User meldet folgendes Problem

### ISSUE THREAD

**Issue by sgse** [gigablue-support-org/templates_PiconsUpdater#41]
PiconsUpdater auf meiner SF4008 installiert (openatv 6), ausgewählt, gelb gedrückt (vorher grün), er hat runtergeladen, danach optimiert und dann leider nix mit Picons.
https://www.opena.tv/plugins/4023-piconsupdater-post303353.html#post303353
https://www.opena.tv/plugins/4023-piconsupdater-post303217.html#post303217
/channelsNotFoundList.txt 
Picons not found for '756' channels
color-ffff00ffard-hd.png;/tmp/piconsupdater/picons-all/4097_0_1_0_0_0_0_0_0_0.png;https://raw.githubusercontent.com/gi...00ffard-hd.png
color-ffdc54d3ard.png;/tmp/piconsupdater/picons-all/4097_0_1_0_0_0_0_0_0_0.png;https://raw.githubusercontent.com/gi...fdc54d3ard.png

Kann jemand helfen?

**Comment by arn354** [comment]
Leider kein blassen was der treibt. Keine Ahnung wo die farbcodes herkommen.

**Comment by sgse** [comment]
Danke.
Tippe mal ins Blaue, Konflikt mit anderer picon Verwaltung. 
Da er wohl der einzige mit dem Problem ist kann dann (erst mal ;) ) hier geschlossen werden.

**Comment by sgse** [comment]
Liegt es evtl. an DVB-T2?, 
setpicon war vorher mal drauf mit nicht gelöschten inträgen in der settings.
https://www.opena.tv/plugins/4023-piconsupdater-new-post.html

Dies ist der Beitrag, der gerade geschrieben wurde:
***************
Hallo sgs,

ich hab gezz mal neu geflasht, via Einstellungsassistent  eingestellt, keine Einstellungen vom vorherigen System übernommen, so  gesehen also alles neu. Piconsupdater installiert als einziges Plugin,  alle Einstellungen so belassen, wie sie sind.Der Picons-Ordner ist  /usr/share/enigma2/picon.
War so eingestellt im Updater.
Picons  geladen, aber wie vorher, keine Anzeige, die Picons haben alle dieselben  "Zahlen-Namen". Also keine Änderung. Ich benutze **DVBT2**.

Laut  diesem Fred  https://www.opena.tv/picons/6265-wo-sollen-die-picons-gespeichert-werden.html  werden die in diesem Ordner auch gesucht.

USB-Ports sind frei, keine Festplatte eingebaut. Ich denke, das Problem ist, daß er die PNGs umbenennt beim laden.

**Comment by arn354** [comment]
was für eine kanalliste und lamedb woher nutzt er denn?
Macht er einen kompletten suchlauf mit vor der suche löschen und hat anschliessend saubere settings/kanalliste?

**Comment by sgse** [comment]
Zitat-Auszug:
Ich habe nur einen DVB-C/T/T2-Tuner, bei der Sendungsinfo (er hat ein png vom OpenWebif angehängt) zeigt er **DVB-S2** an. Am Fernseher steht allerdings auch DVB-T. Vielleicht hilft das auch weiter. 
https://www.opena.tv/plugins/4023-piconsupdater-post303601.html#post303601
------------------------------------------------
Einige Sachen findet er schnell, andere kennt er nicht (lamedb, IPTV, Kanalliste). 
Mir gehen die Ideen aus.

**Comment by arn354** [comment]
Funktioniert bei ihm halt dann einfach nicht. Soll er fertige picons oder piconmanager oder oder oder nehmen. Ich habe keine Ahnung was das bei Ihm los ist,

**Comment by sgse** [comment]
ok
