### ISSUE TITLE
Picon Vorschläge für euronews.

### ISSUE THREAD

**Issue by sgse** [gigablue-support-org/templates_PiconsUpdater#43]
Blau-transparent
![euronews](https://cloud.githubusercontent.com/assets/17575778/26583075/fe96871c-4543-11e7-88cb-7d45c08c475c.png)
Weiß-transparent
![euronews-2](https://cloud.githubusercontent.com/assets/17575778/26583095/0ce118a0-4544-11e7-9a8c-b156673ac002.png)
Weiß-Grau-transparent
![euronews-3](https://cloud.githubusercontent.com/assets/17575778/26583752/b428113e-4546-11e7-85fa-032fb5fd7af2.png)
Weiß auf Blau
![euronews-1](https://cloud.githubusercontent.com/assets/17575778/26583102/1c121086-4544-11e7-93be-897ce6eac930.png)
oder so lassen Blau auf Weiß?
![euronews-d](https://cloud.githubusercontent.com/assets/17575778/26583179/6d406354-4544-11e7-99ef-e9052e69b26e.png)

**Comment by arn354** [comment]
Am besten ist bei dunklen oder weißen Logos wenn man einen 1-2 Pixel breiten Rand in der komplementär Farbe macht.

**Comment by sgse** [comment]
Das wäre bei Blau dann Orange :-) 
![euronews-blau-orange](https://cloud.githubusercontent.com/assets/17575778/26587550/fb3d7a44-4552-11e7-9bfc-88c84c9cf19a.png)
![euronews-weiss-black](https://cloud.githubusercontent.com/assets/17575778/26587567/0565e42a-4553-11e7-9a82-15d488e9727f.png)
Bei Inkscape sind 1-2 Pixel heftig, das sind jetzt 0,2 Pixel.
Nicht so mein Geschmack aber drüber werde ich nicht streiten ;-)

War eh nur ein Vorschlag falls der Text auf transparent besser rein gepasst hätte.

**Comment by mike-99** [comment]
Teste es im Plugin mit unseren dunklen Hintergründen.
Blaue Schrift auf blauem Hintergrund geht garnicht.

**Comment by sgse** [comment]
So, habe mal auf metrix umgestellt, bei kravenHD hatte ich keine Vorschau.
![icon2](https://cloud.githubusercontent.com/assets/17575778/26598556/eb16c6fc-4575-11e7-8f68-bd12707351cb.png)
![icon](https://cloud.githubusercontent.com/assets/17575778/26598724/797a649e-4576-11e7-9cb4-dcd6eb797147.png)
Werde, wenn möglich, bei mir auf Weiß umstellen und in Zukunft auch an die anderen denken :-)
