### ISSUE TITLE
Was passt jetzt am besten ?

### ISSUE THREAD

**Issue by sgse** [gigablue-support-org/templates_PiconsUpdater#49]
![eo-tv](https://user-images.githubusercontent.com/17575778/28995802-1f481226-79f3-11e7-8b30-5c2806a6c09e.png)
![eotv](https://user-images.githubusercontent.com/17575778/28995804-26a467b8-79f3-11e7-9c83-bc7e2214e0c6.png)
Weiß
![eo-tv-grau](https://user-images.githubusercontent.com/17575778/28995805-2d29ac7e-79f3-11e7-8838-07be1b7e90c8.png)
![eo-tv-wg](https://user-images.githubusercontent.com/17575778/28995806-2ff020dc-79f3-11e7-8bd5-b866d252851b.png)
![eo-tv-wb](https://user-images.githubusercontent.com/17575778/28995829-bc1989cc-79f3-11e7-8c78-552a7086e233.png)
weiß-schwarze Schrift
eo-tv.png

**Comment by arn354** [comment]
denke das erste

**Comment by sgse** [comment]
Unterwegs :-)

**Comment by mike-99** [comment]
Probiers doch einfach am TV mit unseren Hintergründen ;)

**Comment by sgse** [comment]
Ich trau mich nicht ;) , habe da jetzt schon zwei Versionen bei der picon Anzeige. Mit und ohne meinen Rahmen.
Hatte erst im Flash gespeichert und dann wieder auf USB-Stick gewechselt, und noch keinen Bock die Ursache zu erforschen.
![dvb12](https://user-images.githubusercontent.com/17575778/28999329-feabd070-7a42-11e7-8aaa-edb78d24337e.png)
