### ISSUE TITLE
new picon for "Filstalwelle"

### ISSUE THREAD

**Issue by McZobel** [gigablue-support-org/templates_PiconsUpdater#63]
![filstalwelle](https://user-images.githubusercontent.com/33523682/32621675-dc25669a-c580-11e7-8091-5bac0ef73d9d.png)
and the sref is: 1_0_1_893F_172_A018_FFFF0000_0_0_0

**Comment by arn354** [comment]
we need the name of the service - you can find in piconupdater log in /tmp/piconupdater
e.g. filstalwelle.png
