### ISSUE TITLE
DVB-T2 RTL NRW & SAT1 NRW (HD)

### ISSUE THREAD

**Issue by MadMakz** [gigablue-support-org/templates_PiconsUpdater#65]
```
rtl-hd-nrw.png;/tmp/piconsupdater/picons-all/1_134_1_0_0_0_0_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/rtl-hd-nrw.png
sat1-hd-nrw.png;/tmp/piconsupdater/picons-all/1_0_1F_4229_4034_2114_EEEE0000_0_0_0.png;https://raw.githubusercontent.com/gigablue-support-org/templates_PiconsUpdater/master/picon_all/sat1-hd-nrw.png
```

![rtl-hd-nrw](https://user-images.githubusercontent.com/3930214/34462591-830bbe52-ee47-11e7-855e-5671f5646dd4.png) 
↑↑ Service reference: 1_0_1F_4209_4004_2114_EEEE0000_0_0_0  ↑↑

![sat1-hd-nrw](https://user-images.githubusercontent.com/3930214/34462592-8323e478-ee47-11e7-82c3-7794bc399cfc.png)

**Comment by mike-99** [comment]
Danke,
die Namen waren leider falsch, die Servicerev. kommt nicht ins Git.
Habe Picons von den schon im Git vorhandenen genommen.

https://github.com/gigablue-support-org/templates_PiconsUpdater/commit/263d22f600e74285e4d4770fa3b46764970cf966
https://github.com/gigablue-support-org/templates_PiconsUpdater/commit/82ef3487e779c9fd64da3e507d22a64a7adca4fc
