### ISSUE TITLE
different channels with the same name

### ISSUE THREAD

**Issue by sunder67** [gigablue-support-org/templates_PiconsUpdater#67]
ATV 
https://www.lyngsat.com/tvchannels/at/ATV.html?&sa=U&ei=vA0cVPOgG6bXyQOelILoCQ&ved=0CEIQFjAG&usg=AFQjCNGN4v3NQLUjezjg2Gk188JJ29mKXQ

https://www.lyngsat.com/tvchannels/tr/ATV-Turkiye.html

**Comment by arn354** [comment]
not possible to distinguish using current logic of piconsupdater.
