### ISSUE TITLE
Radio Berlin 88.8 is now rbb 88.8

### ISSUE THREAD

**Issue by dkadioglu** [gigablue-support-org/templates_PiconsUpdater#68]
Attached is the new logo.
![rbb-888](https://user-images.githubusercontent.com/1633773/52519209-2e79f700-2c58-11e9-88f2-7e86e3649779.png)

**Comment by unityhd** [comment]
commited in...
https://github.com/gigablue-support-org/templates_PiconsUpdater/commit/664d3634cc6ea165e282552d595b89ff3b495ee6
